FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY "Directory.Packages.props" "."
COPY "nuget.*" "."
COPY "CDCService/*.csproj" "CDCService/"
COPY "Domain/*.csproj" "Domain/"
COPY "Kafka/*.csproj" "Kafka/"
COPY "Repository/*.csproj" "Repository/"

RUN dotnet restore "CDCService/CDCService.csproj" \
    /p:TargetFramework=net8.0

WORKDIR /src
COPY . .

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "CDCService/CDCService.csproj" -c $BUILD_CONFIGURATION -o /app/publish  \
    /p:DockerBuild=true /p:UseAppHost=false /p:PublishSingleFile=false  /p:TargetFramework=net8.0 --no-restore

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "CDCService.dll"]
